server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/gateway-demo/protocol/openid-connect/certs

  cloud:
    gateway:
      mvc:
        routes:
        - id: red
          uri: http://localhost:8081
          predicates:
          - Path=/red/**
          